version: '3.9'

services:
  postgres:
    container_name: postgres
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  bot:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    stop_signal: SIGINT
    restart: "unless-stopped"
    depends_on:
      - postgres
