[tool.poetry]
name = "controller"
version = "0.1.0"
description = ""
authors = ["markushik <zem_mark@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dynaconf = "^3.1.11"
loguru = "^0.6.0"
aiogram = "^3.0.0b5"
flake8 = "^5.0.4"
asyncpg = "^0.27.0"
mypy = "^0.982"
sqlalchemy = "^1.4.42"

[[tool.mypy.overrides]]
module = "sqlalchemy.*"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
