REDIS_HOST = "127.0.0.1"

POSTGRES_HOST = "127.0.0.1"
POSTGRES_PORT = "5432"
POSTGRES_USERNAME = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_DATABASE = "postgres"

NATS_HOST = "127.0.0.1"
NATS_PORT = "4222"