name: Checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip3 install --no-cache-dir --upgrade pip
          pip3 install --no-cache-dir flake8
          pip3 install --no-cache-dir flake8-bugbear
      - name: Run flake8
        run: flake8 --ignore=E501, F821 ./app/