name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
         pip3 install --no-cache-dir --upgrade pip
         pip3 install --no-cache-dir poetry
      - name: Install Dependencies
        run: |
          poetry add flake8
          poetry install --only dev
      - name: Run flake8
        run: flake8 ./backend/


