name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          pip3 install --no-cache-dir --upgrade pip
          pip3 install --no-cache-dir poetry
      - name: Install Dependencies
        run: |
          poetry install --only dev --no-root --no-interaction --no-ansi
      - name: Run flake8
        run: |
          poetry run flake8 ./backend/